FROM golang:1.27-alpine@sha256:4cb7ac979db5fcc41cae44b2227ba5ab8a51e8807f40d9ba4dee20a0ad960b5b AS build

WORKDIR /app

COPY go.* ./
RUN go mod download

COPY main.go main.go
RUN CGO_ENABLED=0 go build -o=main

# =====================================================

FROM scratch AS production

# Copy app and front
WORKDIR /app
COPY ./public public

COPY --from=build /app/main /main

EXPOSE 3000
ENTRYPOINT ["/main"]
