version: '3'

services:
  guestbook:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis

  redis:
    image: redis:7@sha256:edfad62e79bbbad4bc6efd528f6a7ca95546f4c0ab5ca504a83952a8cbdc13ae
    ports: 
      - 6379:6379
    volumes:
      - redis-data:/data

volumes:
  redis-data: {}
