version: '3'

services:
  guestbook:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis

  redis:
    image: redis:8@sha256:f0957bcaa75fd58a9a1847c1f07caf370579196259d69ac07f2e27b5b389b021
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data

volumes:
  redis-data: {}
