FROM golang:1.27-alpine@sha256:cf6fca6641884b8433441b2b0652976f975e1d0fdd26d177eaaf8596087f3125 AS build

WORKDIR /app

COPY go.* ./
RUN go mod download

COPY main.go main.go
RUN CGO_ENABLED=0 go build -o=main

# =====================================================

FROM scratch AS production

# Copy app and front
WORKDIR /app
COPY ./public public

COPY --from=build /app/main /main

EXPOSE 3000
ENTRYPOINT ["/main"]
