FROM golang:1.25-alpine@sha256:1ae0735f00daffa3aaf1363a5184c0d2dc55c78e3db4ec70241cdac97bf84b59 AS build

WORKDIR /app

COPY go.* ./
RUN go mod download

COPY main.go main.go
RUN CGO_ENABLED=0 go build -o=main

# =====================================================

FROM scratch AS production

# Copy app and front
WORKDIR /app
COPY ./public public

COPY --from=build /app/main /main

EXPOSE 3000
ENTRYPOINT ["/main"]
